# Site settings
name: Stace`s Blog
email: stacezhou@gmail.com
author: stacezhou
url: http://stacezhou.github.io
#resume_site:
github: https://github.com/stacezhou
baseurl: ""
description:
meta_description: 周辉;个人博客;
motto:
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: stacezhou

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae

theme: jekyll-theme-slate